{"timestamp":"2025-06-28T09:14:37.882145","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-28T09:14:37.883259","level":"info","event":"Filling up the DagBag from /home/rajharit/airflow/dags/meteo_tourism_dags.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-28T09:14:38.518019Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:38.518352Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:38.518646Z","level":"info","event":"Current task name:load_to_database","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:38.518834Z","level":"info","event":"Dag name:weather_tourism_recommendation","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:38.477379","level":"info","event":"Chemin des credentials: /home/rajharit/airflow/dags/credentials/weather_tourism_project.json","logger":"root"}
{"timestamp":"2025-06-28T09:14:38.477654","level":"info","event":"Chemin des données: /home/rajharit/airflow/dags/data/outputs/monthly_weather_scores.csv","logger":"root"}
{"timestamp":"2025-06-28T09:14:38.578413","level":"info","event":"Authentification réussie avec Google Sheets","logger":"root"}
{"timestamp":"2025-06-28T09:14:38.585361","level":"info","event":"Données chargées : 84 lignes","logger":"root"}
{"timestamp":"2025-06-28T09:14:50.749464","level":"error","event":"Erreur de mise à jour du Google Sheet: HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1sPXRdUHMasRur_4Ip5Fw4CDsta9e9KStYJSoVt7asgI?includeGridData=false (Caused by SSLError(SSLError(1, '[SYS] unknown error (_ssl.c:2578)')))","logger":"root"}
{"timestamp":"2025-06-28T09:14:50.749745","level":"error","event":"Erreur critique lors du chargement : HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1sPXRdUHMasRur_4Ip5Fw4CDsta9e9KStYJSoVt7asgI?includeGridData=false (Caused by SSLError(SSLError(1, '[SYS] unknown error (_ssl.c:2578)')))","logger":"root"}
{"timestamp":"2025-06-28T09:14:50.749966","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"SSLError","exc_value":"HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1sPXRdUHMasRur_4Ip5Fw4CDsta9e9KStYJSoVt7asgI?includeGridData=false (Caused by SSLError(SSLError(1, '[SYS] unknown error (_ssl.c:2578)')))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/rajharit/airflow/dags/scripts/load/load_to_db.py","lineno":55,"name":"load_to_database"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/gspread/client.py","lineno":168,"name":"open_by_key"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/gspread/spreadsheet.py","lineno":29,"name":"__init__"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/gspread/spreadsheet.py","lineno":230,"name":"fetch_sheet_metadata"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/gspread/http_client.py","lineno":305,"name":"fetch_sheet_metadata"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/gspread/http_client.py","lineno":114,"name":"request"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/google/auth/transport/requests.py","lineno":540,"name":"request"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/requests/adapters.py","lineno":698,"name":"send"}]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1sPXRdUHMasRur_4Ip5Fw4CDsta9e9KStYJSoVt7asgI?includeGridData=false (Caused by SSLError(SSLError(1, '[SYS] unknown error (_ssl.c:2578)')))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/requests/adapters.py","lineno":667,"name":"send"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/rajharit/airflow_env/lib/python3.10/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}]}]}
{"timestamp":"2025-06-28T09:14:50.801619Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:50.801876Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:50.802006Z","level":"info","event":"Task:<Task(PythonOperator): load_to_database>","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-28T09:14:50.802123Z","level":"info","event":"Failure caused by HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Max retries exceeded with url: /v4/spreadsheets/1sPXRdUHMasRur_4Ip5Fw4CDsta9e9KStYJSoVt7asgI?includeGridData=false (Caused by SSLError(SSLError(1, '[SYS] unknown error (_ssl.c:2578)')))","chan":"stdout","logger":"task"}
